#!/bin/bash/

SCRIPT_SOURCE=${0%/*}

# Install tools
apt install -y git &
apt install -y curl &
apt install -y zsh &
apt install -y firefox &
apt install -y vlc &
apt install -y neovim &
wait

# Git
git config --global user.email "cynosure.north@gmail.com"
git config --global user.name "North"

# Firefox
	# link userchrome
ln -s "$SCRIPT_SOURCE/firefox/chrome" "$HOME/.mozilla/firefox/*.default/chrome"

# ZSH
ln -s "$SCRIPT_SOURCE/.zshrc" "$HOME/.zshrc"

# Gnome
settings set org.gnome.shell.extensions.dash-to-dock show-show-apps-button false
gsettings set org.gnome.shell.extensions.desktop-icons show-home false

#Neovim
ln -s "$SCRIPT_SOURCE/init.vim" "$HOME/.config/nvim/init.vim"
