#!/bin/bash/

# Install tools
apt install -y git &
apt install -y curl &
apt install -y zsh &
apt install -y firefox &
wait

# Git
git config --global user.email "cynosure.north@gmail.com"
git config --global user.name "North"

# Firefox
	# link userchrome
ln -s "$PWD/firefox/chrome" "$HOME/.mozilla/firefox/*.default/chrome"

# Gnome
settings set org.gnome.shell.extensions.dash-to-dock show-show-apps-button false
gsettings set org.gnome.shell.extensions.desktop-icons show-home false
