DYNAMIC_MACRO_ENABLE = yes
LTO_ENABLE = yes
CONSOLE_ENABLE = yes

SWAP_HANDS_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
MAGIC_ENABLE = no
OLED_ENABLE = no
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
