ZDOTDIR="$HOME/.cache/zsh"
[[ ! -d $ZDOTDIR ]] && mkdir -p $ZSH_CACHE

#
#	Completion	(more in completions file later)
#
ZCOMPDUMP=$ZDOTDIR/zcompdump
autoload -U compinit && compinit # -d "$ZCOMPDUMP"\.zwc # "$ZCOMPDUMP"
# Use caching so that commands like apt and dpkg complete are useable
zstyle ':completion:*' use-cache yes

{
	# Compile zcompdump, if modified, to increase startup speed
	if [[ -s "$ZCOMPDUMP" && (! -s "${ZCOMPDUMP}.zwc" || "$ZCOMPDUMP" -nt "${ZCOMPDUMP}.zwc") ]]; then
		autoload -U zrecompile && zrecompile "$zcompdump"
	fi
} &!

#
#	History
#
export HISTFILE=$ZDOTDIR/history
export HISTSIZE=50_000					# How much to load into memory
export SAVEHIST=$HISTSIZE				# How many to write to file

setopt extended_history					# record timestamp of command in HISTFILE
setopt hist_expire_dups_first			# delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt hist_ignore_dups					# ignore duplicated commands history list
setopt hist_find_no_dups				# Histhttps://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/lib/termsupport.zshory won't showhttps://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/lib/termsupport.zsh duplicates on search.
setopt hist_ignore_space				# ignore commands that start with space
setopt hist_verify						# show command with history expansion to user before running it
setopt share_history					# share command history data

#
#	Dirstack
#
DIRSTACKSIZE=10		# tell ZSH to save 10 entries
DIRSTACKFILE=$ZDOTDIR/dirstack
[[ ! -f $DIRSTACKFILE ]] && touch $DIRSTACKFILE
setopt auto_pushd			# Automatically add folders to dirstack on cd
setopt pushd_ignore_dups
setopt pushd_minus			# Swap '+' & '-'

# Save dirstack on exit
function zshexit() {
	print -l ${(u)dirstack} >! $DIRSTACKFILE
}
# And load it on startup
dirstack=( ${(f)"$(< $DIRSTACKFILE)"} )						# load it ( the (f) means split on whitespace (characters defined in $IFS)
[[ -d $dirstack[1] ]] && cd $dirstack[1] && cd $OLDPWD		# Preload #OLDPWD. Arrays are 1 indexed??




setopt multios							# enable redirect to multiple streams: echo >file1 >file2
setopt long_list_jobs					# show long list format job notifications
setopt interactivecomments				# recognize comments
setopt rc_quotes						# Use '' in quoted strings to insert '
setopt noclobber						# '>' fails if the file exists, use '>!' to always overwrite

export EDITOR=nvim
export PAGER=less
export LESSHISTFILE=/dev/null           # Stop less creating a history file


export DATE=$(date +'%Y-%m-%d')

alias bc='bc -q'
alias dl='trash'
alias rm="echo 'use trash (dl) "
alias chromium='chromium-browser --guest --no-default-browser-check'
alias qmv='fd . --color=never -t f | qmv'
alias vlc='cvlc --play-and-exit --fullscreen --no-video-title --mouse-hide-timeout 1 --stereo-mode 1'
alias du='du -sh ./*'
alias hist='fc -il'
alias vi=nvim
alias scr='cd $(mktemp -d)'

alias cpy=wl-copy
alias pst=wl-paste
alias opn=xdg-open

autoload -Uz bracketed-paste-magic		# Maybe can remove
zle -N bracketed-paste bracketed-paste-magic

export PATH=$HOME/.cargo/bin:$PATH	# Rust
export PATH=$HOME/.local/bin:$PATH	# Python

source "$HOME/Coding/dotfiles/zsh/completion.zsh"
source "$HOME/Coding/dotfiles/zsh/keybindings.zsh"
source "$HOME/Coding/dotfiles/zsh/tab-names.zsh"
source "$HOME/Coding/dotfiles/zsh/theme.zsh"

#TODO
# Don't add home folder to dirstack
# Dirstack implementation buggy
# Unified history Buggy
# Slightly slow startup
# Snippets
